language: go

matrix:
  include:
    - go: 1.11.x
    - go: 1.12.x
    - go: tip
  allow_failures:
    - go: tip

notifications:
  email: false

services:
  - redis-server

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
