language: go

go:
  - 1.11.x
  - 1.12.x
  - master

services:
  - redis-server

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
